// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ITa6pTAkYSATlgR7rq1yLBum0QtMLUw',
    appId: '1:587102619157:web:73dfd54d7c9a411250b01c',
    messagingSenderId: '587102619157',
    projectId: 'careconnect-c02ec',
    authDomain: 'careconnect-c02ec.firebaseapp.com',
    storageBucket: 'careconnect-c02ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOf0ZdEpKhMR1953RL_wbIbNJNb-92sE',
    appId: '1:587102619157:android:f28a4aef8496369350b01c',
    messagingSenderId: '587102619157',
    projectId: 'careconnect-c02ec',
    storageBucket: 'careconnect-c02ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYW8UnvuoGHsuosOEcNdLQhHu4zSvAdz4',
    appId: '1:587102619157:ios:f0db4e04f78f2c7550b01c',
    messagingSenderId: '587102619157',
    projectId: 'careconnect-c02ec',
    storageBucket: 'careconnect-c02ec.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYW8UnvuoGHsuosOEcNdLQhHu4zSvAdz4',
    appId: '1:587102619157:ios:f0db4e04f78f2c7550b01c',
    messagingSenderId: '587102619157',
    projectId: 'careconnect-c02ec',
    storageBucket: 'careconnect-c02ec.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ITa6pTAkYSATlgR7rq1yLBum0QtMLUw',
    appId: '1:587102619157:web:bab4e4af45cc60ca50b01c',
    messagingSenderId: '587102619157',
    projectId: 'careconnect-c02ec',
    authDomain: 'careconnect-c02ec.firebaseapp.com',
    storageBucket: 'careconnect-c02ec.firebasestorage.app',
  );
}
